### ISSUE TITLE
Oxford comma

### ISSUE THREAD

**Issue by skiasaurus** [skiasaurus/tau_manifesto#10]
@draialexis: You've added serial/Oxford commas in a number of places, but I'm seeing a number of sources that say the serial comma is nonexistent in French (which agrees with what I've seen in my limited experience). What are your thoughts on this?

**Comment by draialexis** [comment]
My thought can be aptly summed up by: 🤯

I ended up digging a little into the French use of the _virgule_, here's a sort of decision tree I may refer to later for exceptions : 

* by default: no comma in French sentences ❌
	* except if you split similar parts of a same sentence ✅
		* but not if they are tied with **_et_**, _ni_, or _ou_ (Ex: "_Le figuier, l'olivier, le grenadier **et** tous les autres arbres couraient la campagne._ ([Fénélon](https://www.espacefrancais.com/fenelon/))" ❌
			* except 
				* if the propositions on either side of the conjonction are opposed to each other by meaning (Ex: "_J'aime X, et ils préfèrent Y._") ✅
				* if the propositions on either side of the conjonction are too long, by reasonable standards, to be uttuered together in one breath ("_[...], le cerisier de Mandchourie, **et** le chêne à feuille de Myrsine couraient la campagne._" (definitely not Fénélon) ✅
				* if those conjunctions are repeated in list form ✅ ("_L'on doit être et informé, et calme, et responsable._" (examples are hard...))
