### ISSUE TITLE
QED

### ISSUE THREAD

**Issue by skiasaurus** [skiasaurus/tau_manifesto#11]
@draialexis: Your commit message for 8eb4243 makes sense, but can we leave the section header in Latin? Between the change to CFQD in the body text and the hyperlink, I think it'll be easy enough for someone who doesn't know what it means to figure it out.

**Comment by draialexis** [comment]
You make a good point. I'm curious though, why do you think "Quod erat demonstrandum" is a better header than "Ce qu'il fallait démontrer"?

**Comment by skiasaurus** [comment]
Because it's in a foreign language in the original. I'm certain that out of the English speakers who know what "Q.E.D." _means_, only a very few actually know what it _stands for_ in Latin. My suggestion is to keep the same scheme in translation: unfamiliar header, familiar abbreviation in the body.

**Comment by draialexis** [comment]
Approved
