### ISSUE TITLE
Puns section rework

### ISSUE THREAD

**Issue by skiasaurus** [skiasaurus/tau_manifesto#13]
The section on puns has been partly reworked, but the writing as it currently stands feels a little clunky to me.

This issue stems from #3; see the comments there for history.

**Comment by draialexis** [comment]
Oh yes. We have some of the essential parts kinda figured out, but it's not over.

We can deal with issue #12 for now, and leave the general writing as it is until I get to that part of the Manifesto. Don't you think?

**Comment by skiasaurus** [comment]
Certainly; that's why I created them as separate issues. :stuck_out_tongue:

**Comment by draialexis** [comment]
Fair point 😅
