### ISSUE TITLE
"π Is Wrong!"

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#14]
I've tried to change "_π est mauvais_" to "_π n'est pas correct_" at some point, but it created problems down the line so I switched it back. 

The reason why I wanted to change it, is that it sounds weird, and it's hard for me to be more specific. It's not idiomatic. 

I've seen "_π est faux_" [being used](http://www.slate.fr/lien/40467/pi-faux-tau#:~:text=Tau%2C%20repr%C3%A9sentant%20deux%20fois%20la,qui%20correspond%20au%2028%20juin.), and it works better in some regards, but it's still not as good as can be; I think. (By the way, I'll come back to that link at some point to see if I can steal some ideas: they translated some other parts of the Manifesto.)

I may want to re-explore "π n'est pas correct" and find a way to address the problems it creates (in particular, right after Figure 1, Michael highlights how he doesn't mean "incorrect" by saying "wrong"), but even if I get around that, it's still a verbose inelegant title, so different from Palais' "hit song" title.

Not urgent, but important at some point I think.

Thoughts?

**Comment by skiasaurus** [comment]
My thoughts are that it’s just so _strange_ to me that there’s no word in French for this concept—it seems to me like such a basic idea.

That said, it is a slightly odd usage in English; after all, he does feel the need to take a moment to explain exactly what he means by the word “wrong.”

If we don’t come up with anything better, maybe we can leave it in English and explain the meaning in more detail in a footnote?

**Comment by draialexis** [comment]
I see what you mean, but as you point out, it's quite a specific way to use the word. If it was just the phrase "a wrong answer", then sure, "une mauvaise réponse". But it's a broad word, a broad concept, conflicting with a narrow context.

I'll pick some people's brains about it when I get to uni, and yeah, we can always go the translation footnote route.

**Comment by draialexis** [comment]
I'm giving "π est faux!" a try. I guess it _is_ kinda catchy. Might go back on that on my second pass if issues arise, but I'm closing this one for now.

**Comment by skiasaurus** [comment]
I'm a little skeptical, but I really can't find a better solution with the resources at my disposal.

**Comment by skiasaurus** [comment]
How do you feel about _faux_ now that it's been there for a couple of weeks?

**Comment by draialexis** [comment]
I've re-read the whole thing twice since, hunting for typos and weirdnesses, and my eyes glided over that part pretty smoothly I guess. It doesn't feel as good as the original, that's for certain.

**Comment by skiasaurus** [comment]
If you think it's publishable as it is, then you can go ahead and switch out the `wip` tag for `trivial`. (Obviously it isn't actually _trivial_, but the tag simply means that this issue remaining open shouldn't prevent publication.)

**Comment by draialexis** [comment]
Good point ^^

Actually I now recall: what brought me to do that switch was finding references to Palais' article in French, where they called it "π est faux!". Not a lot of references, but still.

"_Faux_" does the job, in my opinion, because it's a word we use a lot in math classes as children. If an answer is wrong, we can dismiss it with a _"c'est faux !"_ : it kinda works the way you guys use "wrong".

Another approach could be something about "_erreur_", "_érroné_" maybe, but it would probably be clunky. Unless we paraphrase that title the way they do when translating movies and books, but it gets unrecognisable past a certain point.

**Comment by skiasaurus** [comment]
> "Faux" does the job, in my opinion, because it's a word we use a lot in math classes as children. If an answer is wrong, we can dismiss it with a "c'est faux !" : it kinda works the way you guys use "wrong".

I think that's actually pretty close to the sense in which Michael means "wrong." Regardless, though, if you think _faux_ does the job, then I'm gonna go ahead and close this.
