### ISSUE TITLE
Italics for foreign words and titles

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#15]
Typically, in French, one would italicise foreign words that have not been "naturalised" ([couple](https://www.btb.termiumplus.gc.ca/tpv2guides/guides/clefsfp/index-fra.html?lang=fra&lettr=indx_catlog_m&page=9H8HupZY8hCg.html) of [references](https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Conventions_typographiques#Mots_%C3%A9trangers)). For instance: 

"et l’on a peut-être remarqué que « τ » et « tour » (en anglais, « turn »)"

should be:

"et l’on a peut-être remarqué que « τ » et « tour » (en anglais, « _turn_ »)"

Note that this is a particular case, where we can probably justify using both italics and quotation marks, because the word refers to itself (so to speak).

We also [italicise](https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Conventions_typographiques#Italique) most titles instead of using quotation marks. **EDIT : "π Is Wrong" is an article! I caught it. My point should still stand for foreign words.**

If that's ok with you, I'll go over the whole text and make the relevant changes soon.

**Comment by draialexis** [comment]
On a less relevant note, I'm amazed at how most serious online ressources for French writing mechanics and grammar seem to come from the Canadian government! 

Not that they're not up to it (they obviously are), but I was expecting the French Academy to be more preminent on that front. I guess they haven't joined the digital age yet.

**Comment by skiasaurus** [comment]
> If that's ok with you, I'll go over the whole text and make the relevant changes soon.

Sounds fine to me.
