### ISSUE TITLE
Figure 16

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#16]
I wipped up a French version of figure 16, after seeing your comment about it in the Word document.

I hope that helps; let me know if I can make it better.

![Nspheres](https://user-images.githubusercontent.com/56820096/91741971-cc744000-ebb5-11ea-961f-6d0e5e33999f.png)

**Comment by skiasaurus** [comment]
Wow, this is great! The only possible improvement I can think of is if the French text were slightly larger, just for the sake of readability.

**Comment by draialexis** [comment]
Sure thing.

**Comment by draialexis** [comment]
![Nspheres](https://user-images.githubusercontent.com/56820096/91778996-8be7e700-ebf4-11ea-9082-3ef6fd7768b6.png)

font size 9

**Comment by draialexis** [comment]
![Nspheres](https://user-images.githubusercontent.com/56820096/91779118-e3865280-ebf4-11ea-9c7f-738bd06ef124.png)
font size 10

**Comment by draialexis** [comment]
![Nspheres](https://user-images.githubusercontent.com/56820096/91779200-1fb9b300-ebf5-11ea-90fd-a0b0c71f1c75.png)
font size 10

**Comment by draialexis** [comment]
![91778996-8be7e700-ebf4-11ea-9082-3ef6fd7768b6](https://user-images.githubusercontent.com/56820096/91779277-57c0f600-ebf5-11ea-81f1-a1a716923659.png)
font size 9 (sorry for the repeated edits ^^)

**Comment by skiasaurus** [comment]
I think 9 pt, but in boldface.

**Comment by draialexis** [comment]
![91778996-8be7e700-ebf4-11ea-9082-3ef6fd7768b6](https://user-images.githubusercontent.com/56820096/91779771-acb13c00-ebf6-11ea-8432-6226a7be86c4.png)
Good call

**Comment by draialexis** [comment]
![Nspheres](https://user-images.githubusercontent.com/56820096/91780202-277a5700-ebf7-11ea-9a05-15aa41fb4d5f.png)
font 10 in bold, just in case.

**Comment by skiasaurus** [comment]
10 pt is actually better, you're right.

I just noticed one other, _exceedingly_ minor thing that could be changed: it has straight quotation marks `" "` instead of typographic/curved ones `“ ”`. But other than that, it's ready.

**Comment by draialexis** [comment]
True. Here:

![Nspheres](https://user-images.githubusercontent.com/56820096/91914311-09286000-ecb8-11ea-8c61-e5158a3b2984.png)

**Comment by skiasaurus** [comment]
Awesome. I'll put it in.

**Comment by skiasaurus** [comment]
Resolved by c4f4b3e.

**Comment by skiasaurus** [comment]
> I just noticed one other, _exceedingly_ minor thing that could be changed: it has straight quotation marks `" "` instead of typographic/curved ones `“ ”`.

I just had a "duh" moment: shouldn't they just be guillemets? 😅

**Comment by draialexis** [comment]
Sure

![Nspheres](https://user-images.githubusercontent.com/56820096/93283575-132a8280-f7d1-11ea-8be7-fd8322878385.png)

**Comment by skiasaurus** [comment]
It appears you may have inadvertently enlarged the font size for each instance of the word _taille_.

**Comment by draialexis** [comment]
> It appears you may have inadvertently enlarged the font size for each instance of the word taille.

That's super weird 🤔

**Comment by draialexis** [comment]
![Nspheres](https://user-images.githubusercontent.com/56820096/93454629-87e9e380-f8db-11ea-95d5-57d1f40cdd43.png)
