### ISSUE TITLE
Link to tauday.com/tau-manifesto

### ISSUE THREAD

**Issue by skiasaurus** [skiasaurus/tau_manifesto#18]
~~Part of #9.~~

The very first words of the original are, amusingly (to me), a link to the page that the reader _is already on_. @draialexis, how do you think we should handle this? Change the URL to (the as-yet-nonexistent) https://tauday.com/le-manifeste-de-tau? Retain the link to the original? Rickroll everyone?

**Comment by draialexis** [comment]
Huh, I hadn't noticed that.

I think I would change the URL as you suggest, and maybe mention it to Michael when handing him the translation.

Unless _we_ get to create the French URL, in the config files or something like that?

> Rickroll everyone?

I'm watching you ಠ_ಠ

**Comment by skiasaurus** [comment]
Okay. We'll do the same thing here, then:

https://github.com/skiasaurus/tau_manifesto/blob/61a338c933daaf232fa08f27f685aeb605cb46a8/chapters/tau_manifesto.tex#L152

**Comment by draialexis** [comment]
Actually, do we know for sure that the "#sec-about_the_author" localiser will / needs to be translated?

**Comment by draialexis** [comment]
Ooooooh I get it now ^^

**Comment by draialexis** [comment]
Applying a fix in 553c592.

I think the `about` links will work. I still have to figure out how `https://tauday.com/le-manifeste-de-tau` will get created: do you know if/how we can do that easily?

Will need to be tested once we're online.

**Comment by skiasaurus** [comment]
> I think the `about` links will work (please confirm if you know).

I made a tweak, shown in a6b1b5e. With your patch, the target URL for the link still began with https://tauday.com/tau-manifesto/, so clicking on it just caused that page (the English version) to open in a new tab in my browser. With mine, the URL begins `.../le-manifeste-de-tau`, and opens to a "page doesn't exist" message (which is the behavior we want for the moment, since the page does not, in fact, exist yet).

> I still have to figure out how `https://tauday.com/le-manifeste-de-tau` will get created: do you know if/how we can do that easily?

I do not. The README on Michael's (and, by extension, our) repo says: "Once the translation is nearing completion, send email to michael@michaelhartl.com for further instructions." So I'm guessing that either 1) the answer to your question may be part of those "further instructions," or 2) this may be something Michael has to do himself.

**Comment by draialexis** [comment]
Awesome sauce, and gotcha.

**Comment by draialexis** [comment]
Which reminds me, this translation _is_ nearing completion. When do you plan to email Michael?

**Comment by skiasaurus** [comment]
Not until you're finished your pass, and no earlier than this weekend. (I also wouldn't necessarily expect a response from Michael until Tuesday, as this will be [a long weekend](https://en.wikipedia.org/wiki/Labor_Day) in the U.S.)

**Comment by skiasaurus** [comment]
Fixed with 87af5d3.
