### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by skiasaurus** [skiasaurus/tau_manifesto#20]
http://tauclock.com appears to be defunct. Can't do anything about it until Michael addresses it in the original.

It's linked to here:

https://github.com/skiasaurus/tau_manifesto/blob/d4e6e22519518e98b567f25d4d6442bc57eb93b9/chapters/tau_manifesto.tex#L1834

**Comment by draialexis** [comment]
Addressed in 0a66fed, after Michael pushed e25efce on the main repo

**Comment by skiasaurus** [comment]
I actually already committed this change directly to `master` with 40f7ed6, but forgot to tag the issue in the commit message. 😆
