### ISSUE TITLE
Uses of 'nevertheless'

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#21]
I'm looking at lines (currently) 1407 & 1408 : 

"Nevertheless, we're still not done with τ."   |   "_Néanmoins, on n'en a toujours pas fini avec τ._"

Yes, "_néanmoins_" is very tightly related to "nevertheless". But I'd like to argue that its use in French is different, if I understand its use in English correctly. Namely, it's _really_ formal.

In this sentence, it feels jarring when it's followed by a colloquial phrase. I assume this effect is not felt in the English version, in which case I'll probably switch "_néanmoins_" for something more common like "_cependant_".

**I guess I'd like to know: is that effect present in the English text as well, and should we preserve it?**

**Comment by skiasaurus** [comment]
"Nevertheless" is formal-_ish_ for _spoken_ English, but not seriously formal; and it certainly wouldn't raise any eyebrows in written English. Examples:

:x: (Spoken) "I know he hasn't scored any goals in their last fifteen games, but nevertheless I think they should keep him in the starting XI."
:heavy_check_mark: (Spoken, as part of a prepared speech) "It was a rough senior year for you, Class of 2021; but nevertheless, I know that you will [blah blah blah commencement speech crap I'm falling asleep just trying to complete this stupid example sentence]."
:heavy_check_mark: ([Written](https://www.nytimes.com/2020/04/20/travel/coronavirus-hotel-openings.html)) "But a handful of hotels are nevertheless moving ahead with planned openings, offering their properties as a port in a very uncertain storm."

**Comment by draialexis** [comment]
Hmmm that's cool. Thank you!

**Comment by skiasaurus** [comment]
... I just realized I never connected all that with your question. :sweat_smile:

Based on your description, it does sound like _cependant_ would be more appropriate for our purposes in all three cases that currently have _néanmoins_.

**Comment by draialexis** [comment]
Oh, hey, forgot about that. Thanks, I took care of it.

**Comment by skiasaurus** [comment]
Just wanted to bring to your attention that there are still two instances of _néanmoins_ in `master`:

https://github.com/skiasaurus/tau_manifesto/blob/f4d383d5b2ea92901b908fc91174256e1b314b44/chapters/tau_manifesto.tex#L773
https://github.com/skiasaurus/tau_manifesto/blob/f4d383d5b2ea92901b908fc91174256e1b314b44/chapters/tau_manifesto.tex#L1396

If this was intentional, you can just close this issue again; I just wanted to make sure it hadn't slipped through the cracks.

**Comment by draialexis** [comment]
I will snipe the second one (supposed to be in a concise section) and let the first one live (Michael is trying to be grandiose here).

**Comment by skiasaurus** [comment]
Bump. :grin:

**Comment by draialexis** [comment]
Woopsie
