### ISSUE TITLE
"I love a nice hack"

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#22]
I think it's important to keep the word "hack" for the effect. Michael is basically doing slam poetry here.

"**Third, as a hacker I love a nice hack.**"

The problem is, while French-speakers can picture a stereotypical hacker, they might not understand what a hack is. It's not in most dictionaries. They might think it's a pirated version of Warcraft III or whatever. It is on Wikipedia though...

I might be worrying about nothing, but what if I made a translator's note or provided a [link](https://fr.wikipedia.org/wiki/Hack) to help them out?

**Comment by skiasaurus** [comment]
So, this is actually sort of another pun. While _hacker_ pretty much always refers to a highly skilled computer user (and conjures up an image for English speakers that I'm sure must be similar to that for French speakers), "hack" is being used more broadly here to mean "A trick, shortcut, skill, or novelty method to increase productivity, efficiency or ease: _'Putting your phone in a sandwich bag when you go to the beach is such a great hack'_" (definition 11 [here](https://en.wiktionary.org/wiki/hack#Noun)).

I don't think it's critical that we keep the wordplay here, as long as we can make the idea understood.

**Comment by draialexis** [comment]
Goot to know, I'll get on that before tomorrow. Thanks.
