### ISSUE TITLE
Yin Yang problem

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#24]
I feel that the whole "**_(sombre, noir, descendant)_**" thing doesn't really work in French. In english, there's some consonance between "dark", "black", and "down." "_Blanc_" and "_montant_" rhyme, so that part is fine for now.

I'll be looking into alliterative or rhyming synonyms; input is welcome.

**Comment by skiasaurus** [comment]
I'm heading to work so I'll have to look at it more in depth at another time, but my first reaction is that this may be overthinking it a little.

**Comment by draialexis** [comment]
Gotcha.

**Comment by skiasaurus** [comment]
I just examined it more closely, and I don't think the alliterations and assonances are intentional here, so it's not something we have to worry about.
