### ISSUE TITLE
Translators' acknowledgment

### ISSUE THREAD

**Issue by skiasaurus** [skiasaurus/tau_manifesto#25]
Alexandre has given his approval for us to mention him by name. Where exactly should we do so?

My first thought is to use a footnote somewhere in the Acknowledgments section.

**Comment by draialexis** [comment]
Sounds good.

**Comment by skiasaurus** [comment]
At the end, like this?

````
... Wyatt et l'homme de la situation\ns \footnote{[Remerciements des traducteurs ici]}.
````

**Comment by draialexis** [comment]
I think that could work.

**Comment by skiasaurus** [comment]
The above commit contains a possible solution. Look good?

**Comment by draialexis** [comment]
Done and merged, thanks.
