### ISSUE TITLE
Paratext translation

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#26]
I translated the paratext (links, banner, newsletter subscription) and put that text in comments for potential future reference. 

Specifically in 0333738, 1d376f6, and 300239b.

Then I realised **no other translators did that**, and indeed, that would be part of translating the website, not just the manifesto.

Do we keep those translation handy, or do we revert? @skiasaurus

**Comment by skiasaurus** [comment]
Revert. That's outside our purview. But I appreciate your enthusiasm. :smile:

**Comment by draialexis** [comment]
On it.
