### ISSUE TITLE
Inapproriate 'on'

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#28]
Re: 8d11ed7

"Why would you want to do that?" | "_Mais pourquoi as-tu fait cela_ ?"

> > What made "_tu_" a more logical choice than "_vous_" in the spot where you used it?

>  Teachers say "_tu_" to pupils, is the basic idea. It's bothered me my whole life.
Pupils say "_tu_" to pupils as well, so that bit of fictionnal dialogue has to use "_tu_" if... the reader is a pupil. All right, yes, that's not necessarily the case.
The current sentence is "_Mais pourquoi as-tu fait cela_ ?", and I think it could be rephrased "_Mais pourquoi faire ça_ ?" or "_Mais pourquoi faire cela_ ?" to address the issue of the pronoun.

My preference goes for "_Mais pourquoi faire ça_ ?", because it's more concise, and the fact that it's more familiar doesn't seem like a problem, here in the FAQ section where the tone is less formal.

**Comment by skiasaurus** [comment]
> My preference goes for "Mais pourquoi faire ça ?"

I agree.

**Comment by draialexis** [comment]
Done
