### ISSUE TITLE
Correct 'expositor'

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#29]
Re: f1c1a92

> I'm only just getting to review some of the changes you've made in detail.
I've looked more into this, and it turns out that neither exposant nor présentateur is a correct translation for English "expositor," which means "a person who explains; a commentator." (While exposant does have a non-mathematical meaning in addition to the one you cite above, the English equivalent of that meaning would be "exhibitor.")
So, perhaps "_explicateur_" or "_commentateur_"?

"_Le commentateur_" sure sounds better than "_l'explicateur_", and can be applied to litterature (as in, critiquing a text) or journalism. "_L'explicateur_" can't really be a person.

Otherwise, we could go for a more specific "_l'enseignant_", which is implied anyway.

**Comment by skiasaurus** [comment]
I think _commentateur_ is closer to Michael’s intent here, so let’s go with that.

**Comment by draialexis** [comment]
Done
