### ISSUE TITLE
Use \ref to reference footnote, OR eliminate the reference

### ISSUE THREAD

**Issue by skiasaurus** [skiasaurus/tau_manifesto#3]
https://github.com/skiasaurus/tau_manifesto/blob/f8348bcc1949b5b9c2ec47d2f628a36480164ed5/chapters/tau_manifesto.tex#L1804

refers to the `\footnote` starting at

https://github.com/skiasaurus/tau_manifesto/blob/f8348bcc1949b5b9c2ec47d2f628a36480164ed5/chapters/tau_manifesto.tex#L1731

This is the only place in the translation where a specific footnote is referenced outside itself. The reference should be a `\ref` instead of a direct inclusion of the footnote number, since the number could change if footnotes are added or deleted earlier in the text.

**Comment by draialexis** [comment]
In general, it might be a useful thing to be able to do. In this instance, I think we might not need to:

The "π in the sky" pun is not a reference that French readers would get -- not usually. Adding a note makes sense, but we could also replace it with a French pun. There's two I can think of that ~~indoctrinate small children with pro-π-ganda~~ help pupils remember π-related formulae: 
* "_Deux pierres_" for the circumference `(2πr)`
* "_Pierre carrée_" for the area `(πr²)`

They're stupid puns and I hate them, but I _will_ give them (or one of them) a platform, for the sake of τ 😬. Just say the word, Sir.

Anyway, if we do that, then we no longer need footnote 26, and the "twice as much pi(e)" footnote can re-use part of footnote 26's text : "_N. du T. : Ce jeu de mots vient du fait qu’en anglais, la lettre grecque π se prononce comme homophone de pie /paɪ/, ce qui signifie « tarte »._"

I hope that makes sense.

**Comment by skiasaurus** [comment]
I love the idea of substituting a similar French pun, especially _because_ you hate them, since Michael's attitude towards "π in the sky" seems similar—I can hear his eyes rolling when I read that sentence. And the approach's potential to render this issue moot is an added bonus.

However, a couple of sentences after "π in the sky," Michael uses the pie pun _again_ to illustrate τ's superiority ("it is not τ that is a piece of π, but π that is a piece of τ"). I didn't add an explanatory note when translating this bit because I figured it would be unnecessary, since footnote 26 (as it currently exists in `master`) would presumably still be fresh in the reader's mind; so if we want to eliminate the cross-reference, we need to find a French alternative for the "piece of π" pun as well.

**Comment by draialexis** [comment]
I missed the "piece of π" pun. Bit of a stretch but damn, it kinda works on π and τ at the same time... 

I don't think `footnote 26` would help French readers understand or recognise it much though: "piece of pie" is a bit removed from "piece of cake", and we have a similar phrase in `FR`, but it's not quite the same: "_c'est pas de la tarte / c'est pas du gâteau_" means it's difficult, and the opposite is usually just "_c'est du gâteau_"(I have no idea why). It would be a messy pun indeed, that comes out of that blender.

Sorry about the random rant. French alternatives then...

Behold, random collection of crappy pun material :
- "_**τ**, c'est pas du gâteau_" (kinda rhymes, lacks π)
- "_**π**, c'est pas du gâ**τ**_" (pretty far-fetched, would need a translator's note too)
- "_haut le **π**ed_" ("easily")
- "_Le **τ** nous dit de ne pas être aux **π**èces_" ("not to be in a rush")
- "_Le **τ** nous retire une é-**π**-ne du **π**ed_" (something helpful, a relief)
-  "_d'un calme olym-**π**-en_" ("exhibiting superhuman calm or patience")
- "_y a pas pho**τ**_" ("without a doute", "there is a clear diference")

What if we were to translate
"**τ**ism tells us: it is not **τ** that is a piece of **π**, but **π** that is a piece of **τ**—one-half **τ**, to be exact." 
as
"_Le **τ** encourage un calme olym-**π**-en / nous dit de ne pas être aux **π**èces, et nous retire une é-**π**-ne du **π**ed_"
instead?

Any other ideas?

**Comment by skiasaurus** [comment]
> I missed the "piece of π" pun. Bit of a stretch but damn, it kinda works on π and τ at the same time...

It is sort of brilliant, isn't it? And that makes it all the more painful that there's no direct equivalent in French. Oh, well; maybe someone (you or a Francophone reader) will come up with something down the road.

>"piece of pie" is a bit removed from "piece of cake"

This is actually the case in English as well—I hadn't thought about a connection between them at all. I associate "piece of π" instead with the idiom "a piece of _the_ pie," meaning one's personal share of a limited resource. (For example, from Pink Floyd's "Money": "Share it fairly, but don't take a slice of my pie.")

That said...

> "_Le **τ** [...] nous dit de ne pas être aux **π**èces, et nous retire une é-**π**-ne du **π**ed_"

If I understand these correctly (aux pièces = piecemeal; épine au pied = thorn in one's side/persistent annoyance), then they're hilarious and we should absolutely use them.

As a side note, I think it's worth pointing out two things about the existing Romance language translations:
- Only the Portuguese appears to do much with this section, so good on us for making an effort.
- In the Portuguese, the approach is the one I took, except that it avoids having a cross-reference by simply rehashing some of the content of the first explanatory footnote in what for us is the second. So, worse comes to worst, that is also an option.

**Comment by draialexis** [comment]
> maybe someone (you or a Francophone reader) will come up with something down the road

Good idea, I'll try to get a few punsters involved on my end.

> the idiom "a piece of the pie," meaning one's personal share of a limited resource.

Ooooh right 🤦‍♂️

> If I understand this correctly (aux pièces = piecemeal[...])

Well not _really_, but yeah I guess. It's about pieces and parts, litterally, but I don't think most people stop to think about that anymore, and only the (admittedly weird) figurative sense remains ("_On n'est pas aux pièces_" -> "We're/I'm not in a rush").

> Although on second thought... doesn't it rely on the English pronunciation of tau/Tao?

🙀 It does. I don't even know how the French pronounce it; could it just be `[to]`?

Oh no, it is. What an oversight. So many moving parts... So many kindergarten puns.

Although `footnote 27` pre-empts that issue somewhat by explaining the τ [taʊ] / Tao thing, so it's probably still ok even if I can't find a way to Frenchify that bit.

> As a side note [...] that is also an option.

I agree, let's not feel like this isn't _adequate_, when in reality it's just not _prefect_.

**Comment by draialexis** [comment]
Here we go. I'm **so** sorry...

Ahem:

 "_La vraie constante du cercle a l'é-**τ**-ffe d'un héro, car elle nous retire une é-**π**-ne du **π**-ed._"

Ugh:

 "_Pourquoi choisir de se prendre les **π**-eds dans le ta-**π**, quand on peut prendre le **τ**-reau par les cornes?_"

Last one: 

"_N'avalez pas la **π**-llule : elle vous resterait sur l'es-**τ**-mac._"

I was obviously lying: 

"_Ils nous prennent pour des **π**-geons; mais on leur donne du fil à re-**τ**-rdre._"

Lightning round NSFW edition: "_Nous avons enfin trouvé le cli-**τ**-ris_", "_Ces traditionalistes **π**-ssent dans un violon_",  "_Le seul recours est de s'en **τ**-rcher le cul_", "_Pourquoi s'obstinent-ils à **π**-sser des lames de rasoir en travers?_"

**Comment by skiasaurus** [comment]
> I'm **so** sorry...

Yeah, right. 🙄

> "_La vraie constante du cercle a l'é-**τ**-ffe d'un héro, car elle nous retire une é-**π**-ne du **π**-ed._"

Not bad.

> "_Pourquoi choisir de se prendre les **π**-eds dans le ta-**π**, quand on peut prendre le **τ**-reau par les cornes?_"

If "prendre les pieds" is approximately equivalent to "drag your feet," then I _really_ like this one; but we can probably take out the bonus "tapis" pun, right? Seems like a bit of a reach (although I do recognize the poetic beauty of having _two_ pi (2π) puns in an essay about tau—no pun intended, ironically).

> "_N'avalez pas la **π**-llule : elle vous resterait sur l'es-**τ**-mac._"

🤮
 
> "_Ils nous prennent pour des **π**-geons; mais on leur donne du fil à re-**τ**-rdre._"

I don't think I understand this one.

> "_Nous avons enfin trouvé le cli-**τ**-ris_"

Speak for yourself. 🏳️‍🌈😛

"_Ces traditionalistes **π**-ssent dans un violon_", "_Le seul recours est de s'en **τ**-rcher le cul_", "_Pourquoi s'obstinent-ils à **π**-sser des lames de rasoir en travers?_"

The rest of these must all have slang meanings and or idioms, because I'm just not getting them at all.

**Comment by draialexis** [comment]
> If "prendre les pieds" is approximately equivalent to "drag your feet," then I really like this one; but we can probably take out the bonus "tapis" pun, right? Seems like a bit of a reach

The phrase "_se prendre les pieds dans le tapis_"  actually means "stumbling, to making a mistake," or by extension "making a fool of oneself (by accident)." It stands or falls with the "_tapis_" I'm afraid.

But! the phrase you were thinking of escaped my notice until you brought it up: "_traîner des pieds._"

"_**Pourquoi traîner des π-eds, quand on peut prendre le τ-reau par les cornes?**_" 

⬆ Do we have a winner? ⬆

The more you know: 
* "_Pigeon_" is a "dupe", and "_donner du fil à retordre_" is "fighting back."
* "_Pisser dans un violon_" is a weird one but a funny one, I find. It means "doing domething utterly useless".

The other two are a bit more on the gross side of things: 
* "_Se torcher de qqch_" (literally: "to wipe oneself") means "not caring in the least about sth."
* "_Pisser des lames de rasoir en travers_" (literally: aïe) means "inflicting great pain on oneself."

**Comment by skiasaurus** [comment]
First off, all this talk about _pisser_ just made me realize that there’s potential for another one based one of my grandfather (who isn’t a native French speaker himself but is married to one)‘s favorite French expressions, _Il pleut comme une vache qui pisse sur une pierre plate_—surely it’s no accident that la vache et le taureau are the same species. `</torture >`

With that out of the way…

> "_**Pourquoi traîner des π-eds, quand on peut prendre le τ-reau par les cornes?**_"
> 
> ⬆ Do we have a winner? ⬆

I might consider changing it from the interrogative to the imperative, but I think so! Regardless of which mood we chose, I think it approaches—even outstrips—the elegance of the original.

Now we just have to figure out precisely how to lead into it—I don’t think we can use “τ-isme nous dit“ because “prendre le taureau par les cornes” doesn’t really sound in line with Taoist principles. 😛 I’m out running an errand right now, but I’ll keep thinking about it.

**Comment by draialexis** [comment]
> Il pleut comme une vache qui pisse sur une pierre plate

Ooh, I don't hear that particular version very often ("_sur une pierre plate_"), but it _must_ speak deeply to any Frenchie. A bit graphic and dated maybe? Tempting though.

> I might consider changing [...] elegance of the original.

Very fair point and thank you.

In the imperative, a few possible versions I've got in mind: 
* "_Ne traînez plus des π-eds : prenez le τ-reau par les cornes!_"
* "_Prenez le τ-reau par les cornes; arrêtez de traîner des π-eds!_"

> doesn’t really sound in line with Taoist principles

Taoism isn't known for animal wrestling, I guess... 🙄 I'll work on it tomorrow to see how it can all come together. 

Going back to my hometown for the day, I'll be reachable by email though.

**Comment by skiasaurus** [comment]
> Ooh, I don't hear that particular version very often ("_sur une pierre plate_"), but it _must_ speak deeply to any Frenchie. A bit graphic and dated maybe? Tempting though.

I didn't mean we should include it! Even if it were appropriate (which it obviously isn't), yours is _much_ better.

> In the imperative, a few possible versions I've got in mind:
> 
> * "_Ne traînez plus des π-eds : prenez le τ-reau par les cornes!_"
> * "_Prenez le τ-reau par les cornes; arrêtez de traîner des π-eds!_"

The first of those is pretty much what I had in mind when I made the suggestion.

> Taoism isn't known for animal wrestling, I guess... 🙄

I'm sure that's true, but I meant more that it's not known for advocating people to take aggressive action on things—in fact, according to [Merriam-Webster](https://www.merriam-webster.com/dictionary/Taoism), it "teaches conformity to the Tao by _unassertive_ action and simplicity" (emphasis added). I'm getting to work on this right now; I think I have a good idea for how to handle it.

**Comment by skiasaurus** [comment]
184c398 shows the structure of one possible solution (some details still need fleshing out).

**Comment by skiasaurus** [comment]
9492180 fulfills the title of this issue, so I'm closing it; any work that remains to be done on this is now contained in separate issues (like #12 and #13).
