### ISSUE TITLE
Rephrase 'at face value'

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#30]
Re: 6b206ae

> A bill/banknote, or something else that has its nominal value printed directly on it (for example, a ticket to a concert or sporting event).

While "face value", when meant literally, does mean "_valeur nominale_" in French, it is not meant literally here. The webpage doesn't have a _valeur nominale_, not commonly speaking anyway. "_Prendre quelque chose pour argent comptant_" still seems like a good fit for an idiom, here, in my opinion.

**Comment by draialexis** [comment]
News Flash: "_Valeur nominale_" can be used figuratively, apparently. It might be an "_anglicisme_", though I haven't found anything to that effect (I mostly find usages in banking and finance, that are valid and undisputed).

I still don't think it's as common or appropriate as "_prendre pour argent comptant_".

**Comment by skiasaurus** [comment]
I didn’t mean to imply that I was taking issue with your decision, I was just trying to provide further context for your newfound understanding of the English idiom. Sorry about that!

**Comment by draialexis** [comment]
Oh man, I feel the previous message didn't convey my tone well _at all_.

I'm not offended in the least, and I suspect it's my bad for using "News Flash" in this context -- I didn't mean for it to sound confrontational, just some discovery I just made.

I've appreciated all your comments, including the one in question.

Sorry about the miscommunication.

**Comment by skiasaurus** [comment]
Not a problem. :smiley:

**Comment by draialexis** [comment]
Thank you 🤗
