### ISSUE TITLE
Lui-même

### ISSUE THREAD

**Issue by skiasaurus** [skiasaurus/tau_manifesto#31]
@draialexis: In your commit message for 3608850, you seem to imply that _lui-même_ is only appropriate when it refers to a person. Is that correct?

If so, there are a bunch of other places that need to be examined (too many to bother listing here).

**Comment by draialexis** [comment]
You know, you're right. That was actually a bad justification for that commit. If you can give a table a personnal pronoun, then you can use "_elle-même_" to refer to it in a sentence.

I still think the change makes the text more fluent, but I need to figure if that's even true -- and if so, why -- and come back to you on that.

**Comment by draialexis** [comment]
I'm reverting back to "_lui-même_", thanks for spotting that.

Just (some of) the facts:

- "_lui/elle-même_" and "_en soi_" both put the spotlight on a specific subject or object.

- on top of that, "_en soi_" puts the spotlight on the essence of that thing.
