### ISSUE TITLE
Sarcasm lost in translation?

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#32]
>[expression]
which bears a striking resemblance to
[expression]

The issue here is that Michael means that they're equal, but says it with a dose of sarcasm.

I'm wondering if the concept of using **resemblance** to reach a mathematical conclusion contains enough sarcasm in itself, or if the French readership will just go "that's not how you do maths!"

Leaning harder into it might get the humour across better : 
"_ce qui ressemble quand même beaucoup à_"

Do you have the same read on this?

**Comment by skiasaurus** [comment]
I think it's probably fine the way it is.
