### ISSUE TITLE
Rework and translate README.md

### ISSUE THREAD

**Issue by skiasaurus** [skiasaurus/tau_manifesto#33]
I don't think we need to include all the info on how to make a translation, since any new ones should be done from the English version anyway.

I will commit my idea for what it could look like on the `readme` branch shortly.

**Comment by skiasaurus** [comment]
@draialexis: Let me know what you think of the English content. Once we've hashed that out, we can turn to translating it. (And by "we" I obviously mean "you.")

**Comment by draialexis** [comment]
Cool idea, I'll get on it ASAP

**Comment by draialexis** [comment]
There doesn't seem to be anything missing from that README

**Comment by skiasaurus** [comment]
Fixed with d3fd582.
