### ISSUE TITLE
Untranslated sentence

### ISSUE THREAD

**Issue by skiasaurus** [skiasaurus/tau_manifesto#36]
The final sentence of the paragraph in section 2.2, describing figures 12 and 13,

> "For reference, both figures show the value of θ (in radians) at each special point."

appears to have never been translated.

**Comment by draialexis** [comment]
I'll be happy to take care of it.

Please indicate the line number, I've been unable to find it so far with a cursory glance or a text search.

**Comment by skiasaurus** [comment]
It should begin at end of https://github.com/skiasaurus/tau_manifesto/blob/87af5d394e4bacd98103f659a7d868c490be9251/chapters/tau_manifesto.tex#L388

**Comment by draialexis** [comment]
﻿Oh I see it now, thanks. I was looking for an English sentence in the French version 😅

I don’t have access to my dev environment until Monday late at night, but you may insert the following to fix the issue: 

Pour information, les deux figures montrent la valeur de $\theta$ (en radians) à chaque point spécial.

Best,
--
Alexis DRAI
drai.alexis@gmail.com
+33 6 63 62 02 77

**Comment by draialexis** [comment]
Done
