### ISSUE TITLE
"gets mapped to[...]"

### ISSUE THREAD

**Issue by draialexis** [skiasaurus/tau_manifesto#8]
Nerd assitance needed. 

"z=a+ib  gets mapped to −a−ib"   |   "_z=a+ib  est caractérisé par −a−ib_"

The transitive verb 'to map sth' is usually translated as '_désigner qqch_' or '_caractériser qqch_'. I think it makes sense to translate 'gets mapped to' as '_est caractérisé par_'.

But that's if `x gets mapped to y <=> y maps to x`

**What I actually wonder is whether** `x maps to y <=> y maps to x`, in which case I can just say "_z=a+ib  désigne −a−ib_" (more elegant).

**Comment by skiasaurus** [comment]
I struggled with this question for a while before finally checking Wiktionary, which, lo and behold, [gave](https://en.wiktionary.org/wiki/map#Verb) the following definition that seems to match Michael's usage here:

> 2. (_mathematics, transitive, followed by a "to" phrase_) To act as a function on something, taking it _to_ something else. "_f_ **maps** _A_ to _B_, **mapping** every _a_ ∈ _A_ to <em>f</em>(<em>a</em>) ∈ _B_."

The same page, under "Translations," gives _mapper_ as a French translation for this sense of the verb. Once I discovered this, I realized it's very likely that this is exactly how I arrived at the translation that I ultimately went with ("z=a+ib est mappé sur -a-ib"). Granted, it would be good to have a more reliable source for this than Wiktionary, and ideally one that also prescribes a preposition to go after it (which probably came from Google Translate, and which I will admit I didn't spend much time verifying.)

**Comment by draialexis** [comment]
All that's good to know, thanks.
